stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: my-react-app
  IMAGE_TAG: latest

test:
  stage: test
  image: node:18-alpine
  script:
    - npm install
    - npm test

build:
  stage: build
  image: node:18-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main
